// Mocks generated by Mockito 5.0.10 from annotations
// in flutter_app/test/fetch_customer_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:ferry/ferry.dart' as _i2;
import 'package:flutter_app/models/customer.dart' as _i3;
import 'package:flutter_app/models/purchase.dart' as _i4;
import 'package:flutter_app/Service/customer_client.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeClient extends _i1.Fake implements _i2.Client {}

class _FakeCustomer extends _i1.Fake implements _i3.Customer {}

class _FakePurchase extends _i1.Fake implements _i4.Purchase {}

/// A class which mocks [CustomerClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerClient extends _i1.Mock implements _i5.CustomerClient {
  MockCustomerClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient()) as _i2.Client);
  @override
  _i6.Future<_i3.Customer> getCustomer() =>
      (super.noSuchMethod(Invocation.method(#getCustomer, []),
              returnValue: Future<_i3.Customer>.value(_FakeCustomer()))
          as _i6.Future<_i3.Customer>);
  @override
  _i6.Future<_i4.Purchase> purchaseOffer(dynamic offerId) =>
      (super.noSuchMethod(Invocation.method(#purchaseOffer, [offerId]),
              returnValue: Future<_i4.Purchase>.value(_FakePurchase()))
          as _i6.Future<_i4.Purchase>);
}
